CFLAGS   += -w $(HTM_RETRIES) $(RETRY_POLICY)

CPPFLAGS := $(CFLAGS)
LIBS     += $(CPPFLAGS) -L/home/shady/lib -ltcmalloc -lrt -lpthread -mcpu=power8 -mtune=power8 -lm
#LIBS     += $(CPPFLAGS) -L/home/shady/lib -ltcmalloc -lrt -lpthread -mhtm -lm
LDFLAGS  += $(LIBS)
